name = "MACEInterface"
uuid = "702af922-8fe5-4898-93bf-1d716fce3ecb"
authors = ["cometscome <cometscome@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2.34"
PythonCall = "0.9.31"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
